obj-$(CONFIG_APWR)		+= powerdk/src/
obj-$(CONFIG_SOCWATCH)		+= socwatchdk/src/
obj-$(CONFIG_SEP3_15)		+= vtunedk/src/
obj-$(CONFIG_PAX)		+= vtunedk/src/pax/
obj-$(CONFIG_VTSSP)	+= vtunedk/src/vtsspp/
